---
title: "Hobotemp"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hobotemp

This is for managing and understanding your HOBO temperature data

## Requirements

  + [R v4+](https://www.r-project.org/)
  + [dplyr](https://CRAN.R-project.org/package=dplyr)
  + [readr](https://CRAN.R-project.org/package=readr)
  + [stringr](https://CRAN.R-project.org/package=stringr)
  + [ggplot2](https://CRAN.R-project.org/package=ggplot2)

## Installation

```
remotes::install_github("rfrancolini/hobotemp")
```

## Read Example Data

```{r example}
library(hobotemp)
x <- read_hobotemp()
x
```

## Draw Example Plot

```{r tempplot}
tempplot_x <- draw_plot(x)
tempplot_x
```

## Read Example Data With User Defined Start/Stop Dates

```{r exampleStartStop}
ss <- as.POSIXct(c("2021-05-20", "2021-06-01"), tz = "EST")
xud <- read_hobotemp(clipped = "user", startstop = ss)
xud
```

## Draw Example Plot User Defined Start/Stop Dates

```{r tempplot_ud}
tempplot_xud <- draw_plot(xud)
tempplot_xud
```

## Read Example Data Without Clipping Data

```{r exampleNA}
xna <- read_hobotemp(clipped = NA)
xna
```

## Draw Example Plot Without Clipping Data

```{r tempplot_na}
tempplot_na <- draw_plot(xna)
tempplot_na
```
